### ISSUE TITLE
move_with_no_delete feature?

### ISSUE THREAD

**Issue by mzagrabe** [getmail6/getmail6#102]
Greetings,

I would like to download mail from an IMAP server (gmail.com) and after downloading the mail, move the downloaded messages to a different folder on the server, but not delete them.

Do you think a feature like this sounds reasonable?

Would you be willing to implement it?

Would you take a pull request?

Thanks for the feedback!

**Comment by rpuntaie** [comment]
I agree that such a feature would fit into the context of getmail.
But ``getmail`` by design outsourced that responsibility.

People use different tools after getmail
(to sort mails into folders, among other tasks):

- via MDA_external + path + arguments:
  ``procmail``, [dovecot-lda](https://wiki2.dovecot.org/HowTo/RefilterMail),
  possibly own script, ...

    ```
    [destination]
    type = MDA_external
    path = /usr/bin/procmail
    arguments = ('-f', '%(sender)', '-m', '<path to procmail config>')
    ```

    ```
    [destination]
    type = MDA_external
    path = /usr/lib/dovecot/dovecot-lda
    arguments = ("-e",)
    ```

- via MDA_lmdp to a local port,
  where e.g. ``dovecot`` server is listening, if set up with protocol LTMP there.
  ``dovecot`` has the ``sieve`` plugin to move mails into folders.

    ```
    [destination]
    type = MDA_lmtp
    host = 127.0.0.1
    port = 23218
    ```

- calling a tool after ``getmail`` has completed,
  to tag, index and possibly resort the mails in ``$MAILDIR``
  into various subfolders (``Maildir`` mailboxes)
  e.g ``notmuch``, which calls ``afew`` via the
  ``~/mail/.notmuch/hooks/post-new`` configuration


Also the filtering of messages has been outsourced:

Examples:

```
[filter-1]
type = Filter_external
path = /usr/bin/spamassassin
ignore_header_shrinkage = True
#pacman -S clamav
[filter-2]
type = Filter_classifier
path = /usr/bin/clamscan
arguments = ('--stdout', '--no-summary', '--scan-mail', '--infected', '-')
exitcodes_drop = (1,)
[filter-3]
type = Filter_external
path = /usr/bin/formail
arguments = ("-a","X-YourName-Refiltered: yes")
exitcodes_drop = ()
```

The last example is from https://wiki2.dovecot.org/HowTo/RefilterMail.
