### ISSUE TITLE
Do not parse hidden files in configuration dir

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [getmail6/getmail6#142]
When run without arguments, `getmail` considers any file in its configuration directory to be a configuration file (except for its own data files). It would make sense to also exclude hidden files (those beginning with a dot) from being parsed (my configuration directory is a git repository for instance and contains a `.gitignore` file which is not a getmail configuration file).

The following patch should fix this.

```diff
--- a/getmail
+++ b/getmail
@@ -682,7 +682,8 @@
             if not os.path.exists(
                 os.path.join(getmaildir,defaults['rcfile'])):
                 options.rcfile = [x for x in os.listdir(getmaildir)
-                                  if not x.startswith('oldmail-')]
+                                  if not (x.startswith('oldmail-')
+                                          or x.startswith('.'))]
             else:
                 options.rcfile.append(defaults['rcfile'])
 
```

**Comment by emtiu** [comment]
It's an edge case, but this might conceivably break someone's setup, if they're using hidden files as actual configuration files. (It sounds silly, but it could be.)

I don't have a good idea how to implement this more safely, because it affects the behavior of getmail before any configuration is read—so we can't make it a config option. Maybe a command line switch like `--ignore-hidden`?

**Comment by rpuntaie** [comment]
This is new in getmail6. We can assume that not many use it yet. The few that do and also use hidden files would just need to rename those files.
