### ISSUE TITLE
Howto resume IDLE after error

### ISSUE THREAD

**Issue by lmoellendorf** [getmail6/getmail6#147]
I am using getmail6 to retrieve mails from Office365 as explained in my comment to [Move to modern authentication(OAuth 2.0) from IMAP for receiving email in Redmine.](https://www.redmine.org/issues/37688#note-17).

After running for several hours getmail6 quits with the error below:
```
wrote 13 uids for SimpleIMAPSSLRetriever:redmine@mydomain.org@outlook.office365.com:993:INBOX
Entering IDLE mode (server says "b'IDLE accepted, awaiting DONE command.'")
IDLE message received
quit() [_retrieverbases.py:1905] trace
IMAP error during logout (socket error: [Errno 32] Broken pipe)
```

How can I tell getmail6 to resume after errors?

**Comment by ykasap** [comment]
I believe there is no way to tell for now.

I also use getmail6 with IMAP IDLE to fetch my inbox from Exchange Online. Once I sent a couple of PRs trying to catch some errors and reconnect during IMAP IDLE. Still, due to my limited Python knowledge, I couldn't catch all errors, especially when the access token expired during a connection and broke the internal state of imaplib unexpectedly. I think that imaplib doesn't expect such errors, and it was difficult for me to distinguish token expiration and other fatal errors cleanly (to reconnect only when a token is expired and exit with other errors), so I gave up.

Currently, I'm using a shell script wrapper to restart getmail after such errors. It is probably the same as just catching all errors internally and reconnecting during IMAP IDLE, but I'm not confident enough to make such a PR. I hope someone with more Python knowledge can do that.

**Comment by lmoellendorf** [comment]
> ..., I couldn't catch all errors, especially when the access token expired during a connection and broke the internal state of imaplib unexpectedly.

I think in this case there is no exception. I assume that the connection is interrupted because the network went down or so (still investigating). What I am asking for is a "retry after error" mode for getmail6. Most of the time a simple reconnect is all what is needed to recover. But if getmail6 does not provide this feature I will look for a tool which monitors and restarts processes (maybe [monit](https://mmonit.com/monit/)?).

**Comment by rpuntaie** [comment]
A solution from outside getmail is probably the easiest.

This should work, but I did not try:

``` sh
cat > ~/.config/systemd/user/getmail.service <<EOF
[Unit]
Description=getmail
StartLimitIntervalSec=300
StartLimitBurst=5
[Service]
ExecStart=/usr/bin/getmail --quiet --idle=INBOX
Restart=on-failure
RestartSec=1s
[Install]
WantedBy=default.target
EOF
systemctl enable --now getmail.service
```

**Comment by lmoellendorf** [comment]
Works with `--user`
```shell
systemctl enable --now --user getmail.service
```
Note that `.getmail/getmailrc` needs to contain absolute paths to the executables for this to work.
