### ISSUE TITLE
Keeping folder organization of source server

### ISSUE THREAD

**Issue by LaXiS96** [getmail6/getmail6#151]
Hello,

is it possible to get a nested Maildir structure that resembles the folders on the server? This was my expectation but after trying with `mailboxes = ALL` it looks like all mail gets dumped to a single Maildir.

As far as I remember with OfflineIMAP I was getting nested Maildirs, can I do the same with getmail?

Thank you

**Comment by ChrisTG742** [comment]
AFAIK getmail6 does not support it directly yet. There's an aproach by someone using a separate python script:
https://blog-lilydjwg-me.translate.goog/2022/4/1/from-getmail6-to-offlineimap.216183.html?_x_tr_sl=auto&_x_tr_tl=de&_x_tr_hl=en&_x_tr_pto=wapp
HTH

**Comment by keithbowes** [comment]
Hm.  Why are you referring to OnlineIMAP in the past tense?  Is there some reason you're not using it if it has the features you want?  (I mean, both OnlineIMAP and getmail6 are written in Python 3.)  The only real disadvantages I'm seeing in OnlineIMAP are:
1. A lack of per-message filtering (e.g. a spam filter), but the argument is that you should be using server-side filtering as not to have to download spam to begin with.  Besides, most mail providers have good spam filtering nowadays.
2. A rather large configuration file compared to fetchmail (multiple INI-file sections instead of something like `poll imap.server.com user 'username' pass 'password' ssl mda 'formail -c >> ~/Mail/Inbox'`), but that's also a problem with getmail (and getmail doesn't let you have more than account per config file).  I do wish that the config files allowed some conditions, like if retrieving mail through an app password fails, then and only then try to do it through OAuth.
3. Only supports maildir, where some popular mail readers support only mbox and maybe MH.  Though, mailx, Mutt, and Evolution all support maildir; that might be a problem for users of clients like Claws or Thunderbird, though.  It's of course supereasy to automate converting maildir to mbox or MH, but then OfflineIMAP won't be able to sync the server for you (surely the primary reason to use OfflineIMAP to begin with).

**Comment by rpuntaie** [comment]
There is no automatic way. You would do just once and everybody does it differently. 

To get the IMAP folder you can use this python script:

``` python
#!/usr/bin/env python

"""
python mk_imap_dirs.py imap.gmail.com 993 $EMAIL $(pass show google/app_password_gmail/$EMAIL)
"""

import sys
import re
from imaplib import IMAP4, IMAP4_SSL

def imap4utf7(s):
    r, d = [], []
    mc = getattr(memoryview, 'cast', lambda *x: x[0])
    s = mc(memoryview(s), 'c')
    def mb64(s):
        s_utf7 = b'+' + s.replace(b',', b'/') + b'-'
        return s_utf7.decode('utf-7')
    for c in s:
        if c == b'&' and not d:
            d.append(b'&')
        elif c == b'-' and d:
            if len(d) == 1:
                r.append(u'&')
            else:
                r.append(mb64(b''.join(d[1:])))
            d = []
        elif d:
            d.append(c)
        else:
            r.append(c.decode())
    if d:
        r.append(mb64(b''.join(d[1:])))
    return u''.join(r)

#z=[b'(\\HasNoChildren) "/" "INBOX"', b'(\\HasChildren \\Noselect) "/" "[Gmail]"', b'(\\Drafts \\HasNoChildren) "/" "[Gmail]/Drafts"', b'(\\HasNoChildren \\Sent) "/" "[Gmail]/Sent Mail"', b'(\\HasNoChildren \\Junk) "/" "[Gmail]/Spam"', b'(\\HasNoChildren \\Trash) "/" "[Gmail]/Trash"']
rex = r'^\s*\((?P<attributes>[^)]*)\)\s+"(?P<delimiter>[^"]+)"\s+("?)(?P<mailbox>.+?)("?)\s*$'
#for i in range(6): print(re.match(rex,imap4utf7(z[i])).groupdict()['mailbox'])

def get_imap_dirs(url, port, login, pw):
    m = port==143 and IMAP4(url) or IMAP4_SSL(url) # port==993
    m.login(login,pw)
    zz= m.list()
    m.logout()
    assert zz[0]=='OK', 'IMAP error listing mailboxes'
    z=zz[1]
    mailboxes = []
    for item in z:
        p = re.match(rex,imap4utf7(item))
        assert p, 'IMAP error parsing mailboxes'
        g = p.groupdict()
        if r'\Noselect' in g['attributes'].split():
            continue
        if not 'All Mail' in g['mailbox']:
            mailboxes.append(g['mailbox'])
    return mailboxes

if __name__ == "__main__":
    imap_dirs = get_imap_dirs( sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4])
    print(imap_dirs)
```

To forward mails to the local folders you can make a getmail config per mailbox:

```
[retriever]
type = SimpleIMAPRetriever
server = mail.example.net
username = jeff.plotzky
password = mailpassword
mailboxes = ("INBOX.spam",)

[destination]
type = Maildir
path = ~jeffp/Maildir/spam/
```

**Comment by vandys** [comment]
Sorry to stir this long-closed issue, but in the hopes that it helps somebody else:

All mails from all mailboxes are pulled into "new", but each has a X-getmail-retrieved-from-mailbox header added.  I've written a script to sweep new/ and move each message into the suitably named folder (prefixed the name with date/time too).  I coded in Dlang, so probably not of wide interest, but the obvious Python script might well belong as an optional tool in the getmail distro?

**Comment by rpuntaie** [comment]
Would you share the D code?

**Comment by vandys** [comment]
Certainly.  However, although I don't care for Python, it's really the right scripting language for this situation, so I converted it.  Note I don't have a Windows machine, nor subfolders.  I wrote the code to handle both, but that aspect isn't tested.  Let me know if it's broken and I'll be happy to fix it.
[folderize.txt](https://github.com/user-attachments/files/16897337/folderize.txt)
