### ISSUE TITLE
SSLv3 issue with "iinet" servers

### ISSUE THREAD

**Issue by BillKen** [getmail6/getmail6#161]
I cannot use getmail-6.18.12 (gentoo) to retrieve mail via sslv3 from the Australian ISP iinet ... I suspect a misconfiguration of _SOME_ of their servers as other email servers in the ISP's parents group work.
The error is:
''_connect() [_retrieverbases.py:663] establishing IMAP SSL connection to mail.iinet.net.au:993 using protocol version TLSV1_2
abort() [_retrieverbases.py:1828] trace
getmailrc: operation error (SSLError during connect ([SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1001)))'

Bug #123 suggests using "ssl_cipher = SSLv3" but this does not work in this case

As a temporary fix I edited "/usr/lib/python3.10/site-packages/getmailcore/_retrieverbases.py"
from:
if ciphers:
        context.set_ciphers(ciphers)
to:
\#if ciphers:
\#        context.set_ciphers(ciphers)
context.set_ciphers('DEFAULT@SECLEVEL=1')

Can someone advise how I can pass 'DEFAULT@SECLEVEL=1' into getmail (ssl_ciphers = 'DEFAULT@SECLEVEL=1' is rejected as invalid in the config file) or another method ... or is this a real bug?

BillK

**Comment by BillKen** [comment]
Some more info:

[retriever]
type = SimpleIMAPSSLRetriever
server = mail.iinet.net.au
port = 993
ssl_version = tlsv1_2
ssl_ciphers = SSLv3
username = x
password =  x

mail ~ # echo | openssl s_client -connect mail.iinet.net.au:993 -brief
CONNECTION ESTABLISHED
Protocol version: TLSv1.2
Ciphersuite: DHE-RSA-AES256-GCM-SHA384
Peer certificate: C = AU, ST = New South Wales, L = North Sydney, O = TPG Telecom Limited, CN = *.iinet.net.au
Hash used: SHA256
Signature type: RSA
Verification: OK
Server Temp Key: DH, 1024 bits
DONE
mail ~ #

openssl ciphers -v -s -tls1_2
...
DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD
...

**Comment by ChrisTG742** [comment]
SSLv3 has been deprecated in 2015, in OpenSSL/LibSSH weak ciphers used by SSL up to v3 have been removed in 2020 at last.
Since almost all tools either rely on OpenSSL's LibSSL or GnuTLS/libGnuTLS, it is no wonder that trying to connect to a service using such an old cipher standard will fail in 2023.

I wonder why you try to run such a strange combination: "ssl_version = tlsv1_2, ssl_ciphers = SSLv3"? Why running SSLv3 on a TLS v1.2 connection?
If the server still runs on SSLv3 in 2023, you should pest your provider to upgrade ASAP or leave to any other provider who takes a bit more care for security IMHO.
