### ISSUE TITLE
mailbox not selectable when maildir name contains space

### ISSUE THREAD

**Issue by fow0ryl** [getmail6/getmail6#34]
Hallo,

don't know if its my fault ...
Never used getmail before. I'm running getmail 6.4 on manjaro linux the first time.

`[retriever]
type = SimpleIMAPSSLRetriever
server = imap.goneo.de
port = 993
username = ...
password = ...
mailboxes = ALL

[destination]
type = Maildir
path = ~/mail/

[options]
verbose = 1
read_all = false
delete = false
delete_after = 7
delete_bigger_than = 1000000
received = false
delivered_to = false
`

When creating folders in the web-interface (roundcube) of my provider, and the folder name contains a space like this one **INBOX/one two**,  I get an error when running getmail.

`mailbox b'INBOX/one two' not selectable (INBOX/one two) - verify the mailbox exists and you have sufficient permissions`

Henning

**Comment by rpuntaie** [comment]
Python imaplib.py should quote mailbox names containing spaces.
There is a bug reported to Python: https://bugs.python.org/issue13940
Since the protocol is handled by Python's imaplib it should be done there.
The bug patch and pull request do not check, whether quotation is already there.
Fixing it in getmail now would produce a problem, when that patch / pull request is included in Python.

**Comment by fow0ryl** [comment]
Ups. No solution for more then 8 years :(
Is imaplib fetching the whole folder tree in only one request?
If getmail is fetching folder by folder it may help to put the path in double quotes without breaking the patch request.

**Comment by rpuntaie** [comment]
I had a closer look at https://github.com/python/cpython/pull/6395.
The pull request probably has not been merge so far because it has some issues:

- password should always be quoted
- quote only if not quoted already (Python 2.7 does so)
- not orthogonal (overlap with other pull requests, why the MapCRLF change?)

I will make the quoting in getmail
and then try to contact @bearbin
and ask him to change the python pull request
to create a behavior like in Python 2.7.

**Comment by rpuntaie** [comment]
Could you verify that it works, before I make a v6.6 for this?

**Comment by fow0ryl** [comment]
Sorry, I did not understand what exactly to verify...

But you can check it yourself if you like.
I have created a test account "getmail6@behrens-exclusiv.de", with just 1MB size and one folder "one two three" in INBOX. To view the mailbox just go to "webmail.goneo.de".
I don't like to write the password here .. Please send a "password request mail" to the test account. I will check it for mails randomly the next days.

In getmail you can use my configuration. Just change username, password and [destination].
username = getmail6@behrens-exclusiv.de

**Comment by rpuntaie** [comment]
If you checked, then there is no need for the test account. Thanks.

**Comment by fow0ryl** [comment]
Sorry, I have to inform you, that there is still an error :)

Messages from folders with names containing a space are not skipped, as files from other folders.
They are delivered every request. Again and again.

First request:
`getmail version 6.6
Copyright (C) 1998-2019 Charles Cazabon.  Licensed under the GNU GPL version 2.
SimpleIMAPSSLRetriever:getmail6@behrens-exclusiv.de@imap.goneo.de:993:
  msg 1/1 (2319 bytes) delivered
  msg 1/1 (2321 bytes) delivered
  2 messages (2321 bytes) retrieved, 4 skipped`

Following requests
`getmail version 6.6
Copyright (C) 1998-2019 Charles Cazabon.  Licensed under the GNU GPL version 2.
SimpleIMAPSSLRetriever:getmail6@behrens-exclusiv.de@imap.goneo.de:993:
  msg 1/1 (2321 bytes) delivered
  1 messages (2321 bytes) retrieved, 5 skipped`

**Comment by rpuntaie** [comment]
OK. Then I should actually accept your offer.
I'll send you a mail to the email you provided.
