### ISSUE TITLE
Shutdown in the middle of a fetch does not write .getmail-data/ file.

### ISSUE THREAD

**Issue by RocketPuppy** [getmail6/getmail6#68]
I'm running getmail in a systemd service. On the first fetch (30,000 mail) I had to shutdown my computer. I assumed getmail would have written the .getmail-data/ file to keep track of the already delivered mail, and restarting would resume where it left off. However it looks like that file wasn't written and restarting the fetch will download everything again. Is there any way I can generate that file from the already delivered mail?

**Comment by rpuntaie** [comment]
Yes, I checked:

- `%(getmaildir)/oldmail-%(server)s-%(port)i-%(username)s-%(mailbox)` has the delivered mail `(msgid,timestamp)`'s. 
- When the mailbox is changed or when `quit`'ing, the file is updated.
- When the process is killed, the file for the current mailbox will not be updated.

So that is the state.
If someone would like to implement a different behavior,
a pull request is welcome.

One could use a memory-mapped file like in this [example](https://stackoverflow.com/questions/5902629/mmap-msync-and-linux-process-termination/5953213#5953213).

**Comment by rpuntaie** [comment]
Regarding creating the oldfiles: You can go through the code (and use some code), parse through the mails and create the oldfiles in the format described by the code.

**Comment by RocketPuppy** [comment]
Thanks. To confirm I have the right code, calling this method with the appropriate arguments should create the file for me: https://github.com/getmail6/getmail6/blob/master/getmailcore/_retrieverbases.py#L833?

**Comment by RocketPuppy** [comment]
Would you open to a PR adding a new getmail command (say getmail-create-oldfile) to recreate that file if it is removed or deleted accidentally?

**Comment by rpuntaie** [comment]
Yes. A separate script, parallel to `getmail` would be best.

**Comment by RocketPuppy** [comment]
Okay, I'll see what I can do. I'm fine to close this issue now. Thanks for your help.
